### ISSUE TITLE
how to compile against Unity3d?

### ISSUE THREAD

**Issue by unruledboy** [gromchen/uSignalR#1]
I can't compile the project, it has over 30 errors without the Newtonsoft.Json (178 with it), for example, it says "JsonProperty" etc. Attribute requires System.Runtime assembly.

**Comment by gromchen** [comment]
I couldn't add "JSON .NET For Unity" library because it is not free, at the same time I used "Newtonsoft.Json" just for example purposes. In addition to this, probably project is quite old, you'll have to update it. It's up to you which JSON library you'll use.

**Comment by bartez** [comment]
@unruledboy,
Actually JSON.NET for unity is free and it works! :) Just remove old Newtonsoft.Json in your project and install asset:
https://www.assetstore.unity3d.com/en/#!/content/11347

**Comment by gromchen** [comment]
@bartez I've updated project with JsonDotNet. Thank you.
